require 'ffi-compiler/compile_task'

begin
FFI::Compiler::CompileTask.new('http-parser-ext') do |t|
  t.cflags << "-Wall -Wextra -O3"
  t.cflags << "-D_GNU_SOURCE=1" if RbConfig::CONFIG["host_os"].downcase =~ /mingw/
end
rescue => e
  puts "$" * 80
  pp e
  puts caller
  puts "$" * 80
  raise
end
